FROM alpine:3.10

LABEL maintainer="Teko Team"

RUN apk --update add coreutils procps
RUN apk add --no-cache curl bash openjdk8-jre python3 py-pip nss libc6-compat \
      && ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2 \
